from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# Main Routes
SRC_PATH = ROOT / "src"
DATA_PATH = ROOT / "data"
OUTPUT_PATH = ROOT / "outputs"

# File Names
VALIDATED_DATA_FILE_NAME = "validated_steam_games.parquet"
FEATURE_ENGINEERED_DATA_FILE_NAME = "feature_engineered_steam_games.parquet"
EDA_OUTPUT_FILE_NAME = "eda_outputs.json"
FE_OUTPUTS_FILE_NAME = "fe_outputs.json"
FE_SCALER_FILE_NAME = "standardScaler.pkl"
TRAINING_3DSCATTER_FILE_NAME = "pca_3d.html"

# Data Routes
RAW_DATA_PATH = "jypenpen54534/steam-games-dataset-2021-2025-65k"
VALIDATED_DATA_PATH = DATA_PATH / VALIDATED_DATA_FILE_NAME
FEATURE_ENGINEERED_DATA_PATH = DATA_PATH / FEATURE_ENGINEERED_DATA_FILE_NAME
EDA_OUTPUT_PARAMS_PATH = OUTPUT_PATH / "params" / EDA_OUTPUT_FILE_NAME
FE_OUTPUT_PARAMS_PATH = OUTPUT_PATH / "params" / FE_OUTPUTS_FILE_NAME
FE_OUTPUT_SCALER_PATH = OUTPUT_PATH / "models" / FE_SCALER_FILE_NAME
TRAINING_OUTPUT_PLOTS_PATH = OUTPUT_PATH / "plots" / TRAINING_3DSCATTER_FILE_NAME
