from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# Main Routes
SRC_PATH = ROOT / "src"
DATA_PATH = ROOT / "data"
OUTPUT_PATH = ROOT / "outputs"

# File Names
VALIDATED_DATA_FILE_NAME = "validated_steam_games.parquet"
FE_WEIGHTED_DATA_FILE_NAME = "fe_weighted_games.parquet"
FE_OHE_DATA_FILE_NAME = "fe_ohe_games.parquet"
EDA_OUTPUT_FILE_NAME = "eda_outputs.json"
FE_OUTPUTS_FILE_NAME = "fe_outputs.json"
FE_SCALER_FILE_NAME = "standardScaler.pkl"
FSTMODEL_3DSCATTER_FILE_NAME = "pca_3d.html"
SNDMODEL_3DSCATTER_FILE_NAME = "famd_3d.html"


# Data Routes
RAW_DATA_PATH = "jypenpen54534/steam-games-dataset-2021-2025-65k"
VALIDATED_DATA_PATH = DATA_PATH / VALIDATED_DATA_FILE_NAME
EDA_OUTPUT_PARAMS_PATH = OUTPUT_PATH / "params" / EDA_OUTPUT_FILE_NAME
FE_WEIGHTED_DATA_PATH = DATA_PATH / FE_WEIGHTED_DATA_FILE_NAME
FE_OHE_DATA_PATH = DATA_PATH / FE_OHE_DATA_FILE_NAME
FE_OUTPUT_PARAMS_PATH = OUTPUT_PATH / "params" / FE_OUTPUTS_FILE_NAME
FE_OUTPUT_SCALER_PATH = OUTPUT_PATH / "models" / FE_SCALER_FILE_NAME
FSTMODEL_OUTPUT_PLOTS_PATH = OUTPUT_PATH / "plots" / FSTMODEL_3DSCATTER_FILE_NAME
SNDMODEL_OUTPUT_PLOTS_PATH = OUTPUT_PATH / "plots" / SNDMODEL_3DSCATTER_FILE_NAME
